name: 'Validate Version'
description: 'Validates that the git tag version matches the version in VERSION.txt'
inputs:
  version-file-path:
    description: 'Path to the VERSION.txt file relative to repository root'
    required: false
    default: 'pymodule/VERSION.txt'
  allow-dev-suffix:
    description: 'Whether to allow -dev suffix in tags'
    required: false
    default: 'false'
outputs:
  version-valid:
    description: 'Whether the version validation passed'
    value: ${{ steps.check_version.outputs.version_valid }}
  tag-version:
    description: 'The version extracted from the git tag'
    value: ${{ steps.check_version.outputs.tag_version }}
  file-version:
    description: 'The version read from the VERSION.txt file'
    value: ${{ steps.check_version.outputs.file_version }}

runs:
  using: 'composite'
  steps:
    - name: Check version match
      id: check_version
      shell: bash
      run: |
        # Extract version from tag (remove 'v' prefix)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "Tag version: $TAG_VERSION"
        echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT

        # Read version from VERSION.txt
        FILE_VERSION=$(cat ${{ inputs.version-file-path }} | tr -d '\n\r ')
        echo "File version: $FILE_VERSION"
        echo "file_version=$FILE_VERSION" >> $GITHUB_OUTPUT

        # Handle dev suffix if allowed
        COMPARE_TAG_VERSION="$TAG_VERSION"
        if [ "${{ inputs.allow-dev-suffix }}" = "true" ]; then
          # Check if tag has -dev suffix
          if [[ "$TAG_VERSION" == *-dev ]]; then
            # Remove -dev suffix for comparison
            COMPARE_TAG_VERSION=${TAG_VERSION%-dev}
            echo "Dev tag detected, comparing version (dev suffix removed): $COMPARE_TAG_VERSION"
          else
            # No -dev suffix when it's expected - this is an error
            echo "version_valid=false" >> $GITHUB_OUTPUT
            echo "Version validation failed: tag '$TAG_VERSION' is missing -dev suffix"
            echo "::error::Dev workflow requires tag with -dev suffix (e.g., v1.0.0-dev)"
            exit 0
          fi
        else
          # Regular workflow - ensure no -dev suffix
          if [[ "$TAG_VERSION" == *-dev ]]; then
            echo "version_valid=false" >> $GITHUB_OUTPUT
            echo "Version validation failed: tag '$TAG_VERSION' has -dev suffix but it's not allowed"
            echo "::error::Regular workflow does not allow -dev suffix in tags"
            exit 0
          fi
        fi

        # Compare versions
        if [ "$COMPARE_TAG_VERSION" = "$FILE_VERSION" ]; then
          echo "version_valid=true" >> $GITHUB_OUTPUT
          echo "Version validation passed"
        else
          echo "version_valid=false" >> $GITHUB_OUTPUT
          echo "Version validation failed: tag '$COMPARE_TAG_VERSION' does not match file '$FILE_VERSION'"
          echo "::warning::Version mismatch - tag: $COMPARE_TAG_VERSION, file: $FILE_VERSION"
        fi
