name: Build Wheels Check

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - 'dev_utils/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/*'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - 'dev_utils/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    name: Build wheels and sdist
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    uses: ./.github/workflows/build-wheels.yml
    with:
      is_dev: false
      linux_x86_build_slang_from_source: false
      run_fvdb_viz_integration: true
    secrets: inherit
